// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OwnHashMap.proto

package com.xian.jdk.proto;

public final class OwnHashMapProto {
  private OwnHashMapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KeyValuePairOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xian.jdk.proto.KeyValuePair)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>.google.protobuf.Any value = 2;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     * @return The value.
     */
    com.google.protobuf.Any getValue();
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getValueOrBuilder();
  }
  /**
   * Protobuf type {@code com.xian.jdk.proto.KeyValuePair}
   */
  public static final class KeyValuePair extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xian.jdk.proto.KeyValuePair)
      KeyValuePairOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KeyValuePair.newBuilder() to construct.
    private KeyValuePair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeyValuePair() {
      key_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new KeyValuePair();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OwnHashMapProto.internal_static_com_xian_jdk_proto_KeyValuePair_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OwnHashMapProto.internal_static_com_xian_jdk_proto_KeyValuePair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KeyValuePair.class, Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object key_ = "";
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @Override
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.Any value_;
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     * @return Whether the value field is set.
     */
    @Override
    public boolean hasValue() {
      return value_ != null;
    }
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     * @return The value.
     */
    @Override
    public com.google.protobuf.Any getValue() {
      return value_ == null ? com.google.protobuf.Any.getDefaultInstance() : value_;
    }
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     */
    @Override
    public com.google.protobuf.AnyOrBuilder getValueOrBuilder() {
      return value_ == null ? com.google.protobuf.Any.getDefaultInstance() : value_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (value_ != null) {
        output.writeMessage(2, getValue());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (value_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof KeyValuePair)) {
        return super.equals(obj);
      }
      KeyValuePair other = (KeyValuePair) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static KeyValuePair parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KeyValuePair parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KeyValuePair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KeyValuePair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KeyValuePair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KeyValuePair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KeyValuePair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KeyValuePair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static KeyValuePair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static KeyValuePair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(KeyValuePair prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xian.jdk.proto.KeyValuePair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xian.jdk.proto.KeyValuePair)
        KeyValuePairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OwnHashMapProto.internal_static_com_xian_jdk_proto_KeyValuePair_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OwnHashMapProto.internal_static_com_xian_jdk_proto_KeyValuePair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                KeyValuePair.class, Builder.class);
      }

      // Construct using com.xian.jdk.proto.OwnHashMapProto.KeyValuePair.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = "";
        value_ = null;
        if (valueBuilder_ != null) {
          valueBuilder_.dispose();
          valueBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OwnHashMapProto.internal_static_com_xian_jdk_proto_KeyValuePair_descriptor;
      }

      @Override
      public KeyValuePair getDefaultInstanceForType() {
        return KeyValuePair.getDefaultInstance();
      }

      @Override
      public KeyValuePair build() {
        KeyValuePair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public KeyValuePair buildPartial() {
        KeyValuePair result = new KeyValuePair(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(KeyValuePair result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = valueBuilder_ == null
              ? value_
              : valueBuilder_.build();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof KeyValuePair) {
          return mergeFrom((KeyValuePair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(KeyValuePair other) {
        if (other == KeyValuePair.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any value_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> valueBuilder_;
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       * @return The value.
       */
      public com.google.protobuf.Any getValue() {
        if (valueBuilder_ == null) {
          return value_ == null ? com.google.protobuf.Any.getDefaultInstance() : value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.Any value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
        } else {
          valueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder setValue(
          com.google.protobuf.Any.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder mergeValue(com.google.protobuf.Any value) {
        if (valueBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            value_ != null &&
            value_ != com.google.protobuf.Any.getDefaultInstance()) {
            getValueBuilder().mergeFrom(value);
          } else {
            value_ = value;
          }
        } else {
          valueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = null;
        if (valueBuilder_ != null) {
          valueBuilder_.dispose();
          valueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public com.google.protobuf.Any.Builder getValueBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : value_;
        }
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getValue(),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xian.jdk.proto.KeyValuePair)
    }

    // @@protoc_insertion_point(class_scope:com.xian.jdk.proto.KeyValuePair)
    private static final KeyValuePair DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new KeyValuePair();
    }

    public static KeyValuePair getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KeyValuePair>
        PARSER = new com.google.protobuf.AbstractParser<KeyValuePair>() {
      @Override
      public KeyValuePair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KeyValuePair> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<KeyValuePair> getParserForType() {
      return PARSER;
    }

    @Override
    public KeyValuePair getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xian.jdk.proto.MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    java.util.List<KeyValuePair>
        getKeyValuesList();
    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    KeyValuePair getKeyValues(int index);
    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    int getKeyValuesCount();
    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    java.util.List<? extends KeyValuePairOrBuilder>
        getKeyValuesOrBuilderList();
    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    KeyValuePairOrBuilder getKeyValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.xian.jdk.proto.MyMessage}
   */
  public static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xian.jdk.proto.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      keyValues_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OwnHashMapProto.internal_static_com_xian_jdk_proto_MyMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OwnHashMapProto.internal_static_com_xian_jdk_proto_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyMessage.class, Builder.class);
    }

    public static final int KEYVALUES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<KeyValuePair> keyValues_;
    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    @Override
    public java.util.List<KeyValuePair> getKeyValuesList() {
      return keyValues_;
    }
    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    @Override
    public java.util.List<? extends KeyValuePairOrBuilder>
        getKeyValuesOrBuilderList() {
      return keyValues_;
    }
    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    @Override
    public int getKeyValuesCount() {
      return keyValues_.size();
    }
    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    @Override
    public KeyValuePair getKeyValues(int index) {
      return keyValues_.get(index);
    }
    /**
     * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
     */
    @Override
    public KeyValuePairOrBuilder getKeyValuesOrBuilder(
        int index) {
      return keyValues_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < keyValues_.size(); i++) {
        output.writeMessage(1, keyValues_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < keyValues_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, keyValues_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyMessage)) {
        return super.equals(obj);
      }
      MyMessage other = (MyMessage) obj;

      if (!getKeyValuesList()
          .equals(other.getKeyValuesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getKeyValuesCount() > 0) {
        hash = (37 * hash) + KEYVALUES_FIELD_NUMBER;
        hash = (53 * hash) + getKeyValuesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xian.jdk.proto.MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xian.jdk.proto.MyMessage)
        MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OwnHashMapProto.internal_static_com_xian_jdk_proto_MyMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OwnHashMapProto.internal_static_com_xian_jdk_proto_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyMessage.class, Builder.class);
      }

      // Construct using com.xian.jdk.proto.OwnHashMapProto.MyMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (keyValuesBuilder_ == null) {
          keyValues_ = java.util.Collections.emptyList();
        } else {
          keyValues_ = null;
          keyValuesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OwnHashMapProto.internal_static_com_xian_jdk_proto_MyMessage_descriptor;
      }

      @Override
      public MyMessage getDefaultInstanceForType() {
        return MyMessage.getDefaultInstance();
      }

      @Override
      public MyMessage build() {
        MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MyMessage buildPartial() {
        MyMessage result = new MyMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(MyMessage result) {
        if (keyValuesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            keyValues_ = java.util.Collections.unmodifiableList(keyValues_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.keyValues_ = keyValues_;
        } else {
          result.keyValues_ = keyValuesBuilder_.build();
        }
      }

      private void buildPartial0(MyMessage result) {
        int from_bitField0_ = bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyMessage) {
          return mergeFrom((MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyMessage other) {
        if (other == MyMessage.getDefaultInstance()) return this;
        if (keyValuesBuilder_ == null) {
          if (!other.keyValues_.isEmpty()) {
            if (keyValues_.isEmpty()) {
              keyValues_ = other.keyValues_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureKeyValuesIsMutable();
              keyValues_.addAll(other.keyValues_);
            }
            onChanged();
          }
        } else {
          if (!other.keyValues_.isEmpty()) {
            if (keyValuesBuilder_.isEmpty()) {
              keyValuesBuilder_.dispose();
              keyValuesBuilder_ = null;
              keyValues_ = other.keyValues_;
              bitField0_ = (bitField0_ & ~0x00000001);
              keyValuesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKeyValuesFieldBuilder() : null;
            } else {
              keyValuesBuilder_.addAllMessages(other.keyValues_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                KeyValuePair m =
                    input.readMessage(
                        KeyValuePair.parser(),
                        extensionRegistry);
                if (keyValuesBuilder_ == null) {
                  ensureKeyValuesIsMutable();
                  keyValues_.add(m);
                } else {
                  keyValuesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<KeyValuePair> keyValues_ =
        java.util.Collections.emptyList();
      private void ensureKeyValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          keyValues_ = new java.util.ArrayList<KeyValuePair>(keyValues_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          KeyValuePair, KeyValuePair.Builder, KeyValuePairOrBuilder> keyValuesBuilder_;

      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public java.util.List<KeyValuePair> getKeyValuesList() {
        if (keyValuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(keyValues_);
        } else {
          return keyValuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public int getKeyValuesCount() {
        if (keyValuesBuilder_ == null) {
          return keyValues_.size();
        } else {
          return keyValuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public KeyValuePair getKeyValues(int index) {
        if (keyValuesBuilder_ == null) {
          return keyValues_.get(index);
        } else {
          return keyValuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public Builder setKeyValues(
          int index, KeyValuePair value) {
        if (keyValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyValuesIsMutable();
          keyValues_.set(index, value);
          onChanged();
        } else {
          keyValuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public Builder setKeyValues(
          int index, KeyValuePair.Builder builderForValue) {
        if (keyValuesBuilder_ == null) {
          ensureKeyValuesIsMutable();
          keyValues_.set(index, builderForValue.build());
          onChanged();
        } else {
          keyValuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public Builder addKeyValues(KeyValuePair value) {
        if (keyValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyValuesIsMutable();
          keyValues_.add(value);
          onChanged();
        } else {
          keyValuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public Builder addKeyValues(
          int index, KeyValuePair value) {
        if (keyValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyValuesIsMutable();
          keyValues_.add(index, value);
          onChanged();
        } else {
          keyValuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public Builder addKeyValues(
          KeyValuePair.Builder builderForValue) {
        if (keyValuesBuilder_ == null) {
          ensureKeyValuesIsMutable();
          keyValues_.add(builderForValue.build());
          onChanged();
        } else {
          keyValuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public Builder addKeyValues(
          int index, KeyValuePair.Builder builderForValue) {
        if (keyValuesBuilder_ == null) {
          ensureKeyValuesIsMutable();
          keyValues_.add(index, builderForValue.build());
          onChanged();
        } else {
          keyValuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public Builder addAllKeyValues(
          Iterable<? extends KeyValuePair> values) {
        if (keyValuesBuilder_ == null) {
          ensureKeyValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, keyValues_);
          onChanged();
        } else {
          keyValuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public Builder clearKeyValues() {
        if (keyValuesBuilder_ == null) {
          keyValues_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          keyValuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public Builder removeKeyValues(int index) {
        if (keyValuesBuilder_ == null) {
          ensureKeyValuesIsMutable();
          keyValues_.remove(index);
          onChanged();
        } else {
          keyValuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public KeyValuePair.Builder getKeyValuesBuilder(
          int index) {
        return getKeyValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public KeyValuePairOrBuilder getKeyValuesOrBuilder(
          int index) {
        if (keyValuesBuilder_ == null) {
          return keyValues_.get(index);  } else {
          return keyValuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public java.util.List<? extends KeyValuePairOrBuilder>
           getKeyValuesOrBuilderList() {
        if (keyValuesBuilder_ != null) {
          return keyValuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(keyValues_);
        }
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public KeyValuePair.Builder addKeyValuesBuilder() {
        return getKeyValuesFieldBuilder().addBuilder(
            KeyValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public KeyValuePair.Builder addKeyValuesBuilder(
          int index) {
        return getKeyValuesFieldBuilder().addBuilder(
            index, KeyValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .com.xian.jdk.proto.KeyValuePair keyValues = 1;</code>
       */
      public java.util.List<KeyValuePair.Builder>
           getKeyValuesBuilderList() {
        return getKeyValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          KeyValuePair, KeyValuePair.Builder, KeyValuePairOrBuilder>
          getKeyValuesFieldBuilder() {
        if (keyValuesBuilder_ == null) {
          keyValuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              KeyValuePair, KeyValuePair.Builder, KeyValuePairOrBuilder>(
                  keyValues_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          keyValues_ = null;
        }
        return keyValuesBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xian.jdk.proto.MyMessage)
    }

    // @@protoc_insertion_point(class_scope:com.xian.jdk.proto.MyMessage)
    private static final MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyMessage();
    }

    public static MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xian_jdk_proto_KeyValuePair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xian_jdk_proto_KeyValuePair_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xian_jdk_proto_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xian_jdk_proto_MyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020OwnHashMap.proto\022\022com.xian.jdk.proto\032\031" +
      "google/protobuf/any.proto\"@\n\014KeyValuePai" +
      "r\022\013\n\003key\030\001 \001(\t\022#\n\005value\030\002 \001(\0132\024.google.p" +
      "rotobuf.Any\"@\n\tMyMessage\0223\n\tkeyValues\030\001 " +
      "\003(\0132 .com.xian.jdk.proto.KeyValuePairB%\n" +
      "\022com.xian.jdk.protoB\017OwnHashMapProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_xian_jdk_proto_KeyValuePair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xian_jdk_proto_KeyValuePair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xian_jdk_proto_KeyValuePair_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_xian_jdk_proto_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xian_jdk_proto_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xian_jdk_proto_MyMessage_descriptor,
        new String[] { "KeyValues", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
